name: custom-job
description: custom action

inputs:
  name:
    description: "The name to greet"
    required: true

# For JS
# runs:
#   using: "node20"
#   main: "dist/index.js"

# For Docker
runs:
  using: docker
  image: Dockerfile
  env:
    NAME: ${{ inputs.name }}
